services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Add this line to map your local 'sql' folder to the initialization directory:
      - ./sql:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

#  app:
#    build: .
#    container_name: spring_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
#      - SPRING_DATASOURCE_USERNAME=${USERNAME}
#      - SPRING_DATASOURCE_PASSWORD=${PASSWD}
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  postgres_data:
